export interface MapCatalogEntry {
  id: number
  hex: string
  name: string
  label: string
}

// Mirrors red/state/map_names.go so the public world browser can resolve the
// same map names that appear in run failures and debugging output without a
// separate CLI lookup. Map geometry still comes from /maps/{id}.json.
const RAW_MAPS = `
00 PALLET_TOWN
01 VIRIDIAN_CITY
02 PEWTER_CITY
03 CERULEAN_CITY
04 LAVENDER_TOWN
05 VERMILION_CITY
06 CELADON_CITY
07 FUCHSIA_CITY
08 CINNABAR_ISLAND
09 INDIGO_PLATEAU
0A SAFFRON_CITY
0B UNUSED_MAP_0B
0C ROUTE_1
0D ROUTE_2
0E ROUTE_3
0F ROUTE_4
10 ROUTE_5
11 ROUTE_6
12 ROUTE_7
13 ROUTE_8
14 ROUTE_9
15 ROUTE_10
16 ROUTE_11
17 ROUTE_12
18 ROUTE_13
19 ROUTE_14
1A ROUTE_15
1B ROUTE_16
1C ROUTE_17
1D ROUTE_18
1E ROUTE_19
1F ROUTE_20
20 ROUTE_21
21 ROUTE_22
22 ROUTE_23
23 ROUTE_24
24 ROUTE_25
25 REDS_HOUSE_1F
26 REDS_HOUSE_2F
27 BLUES_HOUSE
28 OAKS_LAB
29 VIRIDIAN_POKECENTER
2A VIRIDIAN_MART
2B VIRIDIAN_SCHOOL_HOUSE
2C VIRIDIAN_NICKNAME_HOUSE
2D VIRIDIAN_GYM
2E DIGLETTS_CAVE_ROUTE_2
2F VIRIDIAN_FOREST_NORTH_GATE
30 ROUTE_2_TRADE_HOUSE
31 ROUTE_2_GATE
32 VIRIDIAN_FOREST_SOUTH_GATE
33 VIRIDIAN_FOREST
34 MUSEUM_1F
35 MUSEUM_2F
36 PEWTER_GYM
37 PEWTER_NIDORAN_HOUSE
38 PEWTER_MART
39 PEWTER_SPEECH_HOUSE
3A PEWTER_POKECENTER
3B MT_MOON_1F
3C MT_MOON_B1F
3D MT_MOON_B2F
3E CERULEAN_TRASHED_HOUSE
3F CERULEAN_TRADE_HOUSE
40 CERULEAN_POKECENTER
41 CERULEAN_GYM
42 BIKE_SHOP
43 CERULEAN_MART
44 MT_MOON_POKECENTER
45 CERULEAN_TRASHED_HOUSE_COPY
46 ROUTE_5_GATE
47 UNDERGROUND_PATH_ROUTE_5
48 DAYCARE
49 ROUTE_6_GATE
4A UNDERGROUND_PATH_ROUTE_6
4B UNDERGROUND_PATH_ROUTE_6_COPY
4C ROUTE_7_GATE
4D UNDERGROUND_PATH_ROUTE_7
4E UNDERGROUND_PATH_ROUTE_7_COPY
4F ROUTE_8_GATE
50 UNDERGROUND_PATH_ROUTE_8
51 ROCK_TUNNEL_POKECENTER
52 ROCK_TUNNEL_1F
53 POWER_PLANT
54 ROUTE_11_GATE_1F
55 DIGLETTS_CAVE_ROUTE_11
56 ROUTE_11_GATE_2F
57 ROUTE_12_GATE_1F
58 BILLS_HOUSE
59 VERMILION_POKECENTER
5A POKEMON_FAN_CLUB
5B VERMILION_MART
5C VERMILION_GYM
5D VERMILION_PIDGEY_HOUSE
5E VERMILION_DOCK
5F SS_ANNE_1F
60 SS_ANNE_2F
61 SS_ANNE_3F
62 SS_ANNE_B1F
63 SS_ANNE_BOW
64 SS_ANNE_KITCHEN
65 SS_ANNE_CAPTAINS_ROOM
66 SS_ANNE_1F_ROOMS
67 SS_ANNE_2F_ROOMS
68 SS_ANNE_B1F_ROOMS
69 UNUSED_MAP_69
6A UNUSED_MAP_6A
6B UNUSED_MAP_6B
6C VICTORY_ROAD_1F
6D UNUSED_MAP_6D
6E UNUSED_MAP_6E
6F UNUSED_MAP_6F
70 UNUSED_MAP_70
71 LANCES_ROOM
72 UNUSED_MAP_72
73 UNUSED_MAP_73
74 UNUSED_MAP_74
75 UNUSED_MAP_75
76 HALL_OF_FAME
77 UNDERGROUND_PATH_NORTH_SOUTH
78 CHAMPIONS_ROOM
79 UNDERGROUND_PATH_WEST_EAST
7A CELADON_MART_1F
7B CELADON_MART_2F
7C CELADON_MART_3F
7D CELADON_MART_4F
7E CELADON_MART_ROOF
7F CELADON_MART_ELEVATOR
80 CELADON_MANSION_1F
81 CELADON_MANSION_2F
82 CELADON_MANSION_3F
83 CELADON_MANSION_ROOF
84 CELADON_MANSION_ROOF_HOUSE
85 CELADON_POKECENTER
86 CELADON_GYM
87 GAME_CORNER
88 CELADON_MART_5F
89 GAME_CORNER_PRIZE_ROOM
8A CELADON_DINER
8B CELADON_CHIEF_HOUSE
8C CELADON_HOTEL
8D LAVENDER_POKECENTER
8E POKEMON_TOWER_1F
8F POKEMON_TOWER_2F
90 POKEMON_TOWER_3F
91 POKEMON_TOWER_4F
92 POKEMON_TOWER_5F
93 POKEMON_TOWER_6F
94 POKEMON_TOWER_7F
95 MR_FUJIS_HOUSE
96 LAVENDER_MART
97 LAVENDER_CUBONE_HOUSE
98 FUCHSIA_MART
99 FUCHSIA_BILLS_GRANDPAS_HOUSE
9A FUCHSIA_POKECENTER
9B WARDENS_HOUSE
9C SAFARI_ZONE_GATE
9D FUCHSIA_GYM
9E FUCHSIA_MEETING_ROOM
9F SEAFOAM_ISLANDS_B1F
A0 SEAFOAM_ISLANDS_B2F
A1 SEAFOAM_ISLANDS_B3F
A2 SEAFOAM_ISLANDS_B4F
A3 VERMILION_OLD_ROD_HOUSE
A4 FUCHSIA_GOOD_ROD_HOUSE
A5 POKEMON_MANSION_1F
A6 CINNABAR_GYM
A7 CINNABAR_LAB
A8 CINNABAR_LAB_TRADE_ROOM
A9 CINNABAR_LAB_METRONOME_ROOM
AA CINNABAR_LAB_FOSSIL_ROOM
AB CINNABAR_POKECENTER
AC CINNABAR_MART
AD CINNABAR_MART_COPY
AE INDIGO_PLATEAU_LOBBY
AF COPYCATS_HOUSE_1F
B0 COPYCATS_HOUSE_2F
B1 FIGHTING_DOJO
B2 SAFFRON_GYM
B3 SAFFRON_PIDGEY_HOUSE
B4 SAFFRON_MART
B5 SILPH_CO_1F
B6 SAFFRON_POKECENTER
B7 MR_PSYCHICS_HOUSE
B8 ROUTE_15_GATE_1F
B9 ROUTE_15_GATE_2F
BA ROUTE_16_GATE_1F
BB ROUTE_16_GATE_2F
BC ROUTE_16_FLY_HOUSE
BD ROUTE_12_SUPER_ROD_HOUSE
BE ROUTE_18_GATE_1F
BF ROUTE_18_GATE_2F
C0 SEAFOAM_ISLANDS_1F
C1 ROUTE_22_GATE
C2 VICTORY_ROAD_2F
C3 ROUTE_12_GATE_2F
C4 VERMILION_TRADE_HOUSE
C5 DIGLETTS_CAVE
C6 VICTORY_ROAD_3F
C7 ROCKET_HIDEOUT_B1F
C8 ROCKET_HIDEOUT_B2F
C9 ROCKET_HIDEOUT_B3F
CA ROCKET_HIDEOUT_B4F
CB ROCKET_HIDEOUT_ELEVATOR
CC UNUSED_MAP_CC
CD UNUSED_MAP_CD
CE UNUSED_MAP_CE
CF SILPH_CO_2F
D0 SILPH_CO_3F
D1 SILPH_CO_4F
D2 SILPH_CO_5F
D3 SILPH_CO_6F
D4 SILPH_CO_7F
D5 SILPH_CO_8F
D6 POKEMON_MANSION_2F
D7 POKEMON_MANSION_3F
D8 POKEMON_MANSION_B1F
D9 SAFARI_ZONE_EAST
DA SAFARI_ZONE_NORTH
DB SAFARI_ZONE_WEST
DC SAFARI_ZONE_CENTER
DD SAFARI_ZONE_CENTER_REST_HOUSE
DE SAFARI_ZONE_SECRET_HOUSE
DF SAFARI_ZONE_WEST_REST_HOUSE
E0 SAFARI_ZONE_EAST_REST_HOUSE
E1 SAFARI_ZONE_NORTH_REST_HOUSE
E2 CERULEAN_CAVE_2F
E3 CERULEAN_CAVE_B1F
E4 CERULEAN_CAVE_1F
E5 NAME_RATERS_HOUSE
E6 CERULEAN_BADGE_HOUSE
E7 UNUSED_MAP_E7
E8 ROCK_TUNNEL_B1F
E9 SILPH_CO_9F
EA SILPH_CO_10F
EB SILPH_CO_11F
EC SILPH_CO_ELEVATOR
ED UNUSED_MAP_ED
EE UNUSED_MAP_EE
EF TRADE_CENTER
F0 COLOSSEUM
F1 UNUSED_MAP_F1
F2 UNUSED_MAP_F2
F3 UNUSED_MAP_F3
F4 UNUSED_MAP_F4
F5 LORELEIS_ROOM
F6 BRUNOS_ROOM
F7 AGATHAS_ROOM
`

function displayName(name: string): string {
  return name
    .split('_')
    .map((part) => /^(\d+F|B\d+F|SS|CO)$/.test(part) ? part : part.charAt(0) + part.slice(1).toLowerCase())
    .join(' ')
    .replace(/Pokemon/g, 'Pokémon')
    .replace(/Oaks/g, "Oak's")
    .replace(/Reds/g, "Red's")
    .replace(/Blues/g, "Blue's")
}

export const MAP_CATALOG: MapCatalogEntry[] = RAW_MAPS.trim().split('\n').map((line) => {
  const [hex, name] = line.trim().split(/\s+/, 2)
  return {
    id: Number.parseInt(hex, 16),
    hex,
    name,
    label: displayName(name)
  }
})

const BY_ID = new Map(MAP_CATALOG.map((entry) => [entry.id, entry]))
const BY_NAME = new Map(MAP_CATALOG.map((entry) => [entry.name.toUpperCase(), entry]))

export function mapEntry(id: number): MapCatalogEntry | undefined {
  return BY_ID.get(Math.max(0, Math.min(255, Math.trunc(id))))
}

export function resolveMapQuery(value: string | null | undefined): MapCatalogEntry | undefined {
  const raw = String(value || '').trim()
  if (!raw) return undefined
  const normalized = raw.toUpperCase().replace(/[\s-]+/g, '_')
  const named = BY_NAME.get(normalized)
  if (named) return named
  const numeric = /^0X[0-9A-F]+$/i.test(raw)
    ? Number.parseInt(raw.slice(2), 16)
    : /^[0-9A-F]{2}$/i.test(raw) && /[A-F]/i.test(raw)
      ? Number.parseInt(raw, 16)
      : /^\d+$/.test(raw)
        ? Number.parseInt(raw, 10)
        : Number.NaN
  return Number.isFinite(numeric) ? mapEntry(numeric) : undefined
}
